version: '3'
services:
  app:
    image: spring-app
    restart: always
    build: .
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306

  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: personasdb
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./my-datavolume:/var/lib/mysql
