#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: delete-deployment
  labels:
    app: delete
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delete
  template:
    metadata:
      labels:
        app: delete
    spec:
      containers:
        - name: delete
          image: thepixels21/spring-delete
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_PORT
              value: "3306"
      restartPolicy: Always
---
#Service
apiVersion: v1
kind: Service
metadata:
  name: delete-service
spec:
  type: NodePort
  selector:
    app: delete
  ports:
  - protocol: TCP
    port: 8084
    targetPort: 8080
