#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: read-deployment
  labels:
    app: read
spec:
  replicas: 1
  selector:
    matchLabels:
      app: read
  template:
    metadata:
      labels:
        app: read
    spec:
      containers:
        - name: read
          image: thepixels21/spring-read
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_PORT
              value: "3306"
      restartPolicy: Always
---
#Service
apiVersion: v1
kind: Service
metadata:
  name: read-service
spec:
  type: NodePort
  selector:
    app: read
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8080
